name: Keep Supabase Alive
on:
  schedule:
    # Se ejecuta a las 00:00 cada 2 días
    - cron: '0 0 */2 * *'
  workflow_dispatch: # Permite ejecutarlo manualmente si quieres

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Hacer petición a Supabase
        run: |
          curl -f -X GET "https://jvxqrswxrlnavtgrlgzs.supabase.co/auth/v1/health?bust=${{ github.run_id }}" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Cache-Control: no-cache"
